version: '3.1'

services:

  image-hosting-apache:
    build:
      dockerfile: "./php_apache/Dockerfile"
    ports:
      - "8080:80"
      - "443:443"
    environment:
      TZ: 'Europe/Moscow'
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    volumes:
      - ./src:/var/www/html
      - ./uploads/user_pictures:/var/www/html/uploads/user_pictures
    networks:
      - image-hosting
    depends_on:
      - db

  db:
    image: mysql:5.7.32
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./image-hosting_db:/var/lib/mysql
    networks:
      - image-hosting
    ports:
      - "3306:3306"

networks:
  image-hosting: